name: Syngine CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  quick-build:
    if: github.event_name == 'push' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Init required submodules
        run: >
          git submodule update --init --recursive
          third_party/SDL
          third_party/bgfx.cmake
          third_party/assimp
          third_party/JoltPhysics

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure
        run: >
          cmake -B build -S .
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DSYNGINE_BUILD_TOOLS=OFF
          ${{ matrix.os != 'windows-latest' && '-DSDL_UNIX_CONSOLE_BUILD=ON' || '' }}

      - name: Build
        run: cmake --build build

  full-build:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Init required submodules
        run: >
          git submodule update --init --recursive
          third_party/SDL
          third_party/bgfx.cmake
          third_party/assimp
          third_party/JoltPhysics

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure
        run: >
          cmake -B build -S .
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DSYNGINE_BUILD_TOOLS=OFF
          ${{ matrix.os != 'windows-latest' && '-DSDL_UNIX_CONSOLE_BUILD=ON' || '' }}

      - name: Build
        run: cmake --build build