name: Generate Lua Docs

on:
  push:
    branches:
      - dev

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # so we can push back
      
      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          lua-version: '5.4'

      - name: Run lua
        run: lua main.lua
        working-directory: ./docs/lua

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate Lua documentation"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: "docs/ docs/api"